import type { CapabilityProofExpectation, CapabilityProofFailureReason, Es256PublicJwk } from "@opencrane/models/authorization";
import type { AgentRuntimeProjectedTokenAudience, ManagedAgentRuntimeProjectedTokenAudience } from "@opencrane/contracts";

/** Projected-token audience accepted by exactly one personal or managed runtime plane. */
type RuntimeProjectedTokenAudience = AgentRuntimeProjectedTokenAudience | ManagedAgentRuntimeProjectedTokenAudience;

/** One-time bootstrap claim bound to the exact runtime attempt and Pod identity. */
export interface RuntimeBootstrapClaim
{
	/** Globally unique one-time bootstrap identifier. */
	readonly bootstrapId: string;
	/** Silo containing the runtime. */
	readonly siloId: string;
	/** Fixed control-plane audience for the projected workload token. */
	readonly audience: RuntimeProjectedTokenAudience;
	/** Subject authorized to bootstrap the runtime. */
	readonly subjectId: string;
	/** Exact projected Kubernetes service account. */
	readonly serviceAccountName: string;
	/** Exact Kubernetes namespace. */
	readonly namespace: string;
	/** Controller-managed workload kind being bootstrapped. */
	readonly workloadKind: "job" | "deployment";
	/** Exact immutable UID of the Job or Deployment. */
	readonly workloadUid: string;
	/** Exact immutable runtime Pod UID. */
	readonly podUid: string;
	/** Logical run authority identifier. */
	readonly runId: string;
	/** Stable AgentService executed by the workload. */
	readonly agentServiceId: string;
	/** Positive run attempt being bootstrapped. */
	readonly attempt: number;
	/** Immutable revision loaded by the runtime. */
	readonly agentRevisionId: string;
	/** Proposed public P-256 key generated by the runtime for this run binding. */
	readonly proofPublicJwk: Es256PublicJwk;
	/** Runtime-proposed RFC 7638 thumbprint, verified from the public JWK before binding. */
	readonly proofKeyThumbprint: string;
	/** Epoch-millisecond hard expiry. */
	readonly expiresAtEpochMs: number;
}

/** Trusted facts expected while consuming a bootstrap claim. */
export interface RuntimeBootstrapExpectation
{
	/** Expected silo. */
	readonly siloId: string;
	/** Fixed control-plane audience expected from the projected workload token. */
	readonly audience: RuntimeProjectedTokenAudience;
	/** Expected subject. */
	readonly subjectId: string;
	/** Expected projected Kubernetes service account. */
	readonly serviceAccountName: string;
	/** Expected Kubernetes namespace. */
	readonly namespace: string;
	/** Expected controller-managed workload kind. */
	readonly workloadKind: "job" | "deployment";
	/** Expected immutable UID of the Job or Deployment. */
	readonly workloadUid: string;
	/** Expected immutable runtime Pod UID. */
	readonly podUid: string;
	/** Expected logical run identifier. */
	readonly runId: string;
	/** Expected stable AgentService identifier. */
	readonly agentServiceId: string;
	/** Expected current run attempt. */
	readonly attempt: number;
	/** Expected immutable agent revision. */
	readonly agentRevisionId: string;
	/** Trusted current epoch-millisecond time. */
	readonly nowEpochMs: number;
}

/** Stable reason a runtime bootstrap failed closed. */
export type RuntimeBootstrapFailureReason = "invalid_bootstrap" | "invalid_workload_kind" | "invalid_proof_key" | "projected_token_audience_mismatch" | "silo_mismatch" | "subject_mismatch" | "service_account_mismatch" | "namespace_mismatch" | "workload_kind_mismatch" | "workload_uid_mismatch" | "pod_mismatch" | "agent_service_mismatch" | "run_mismatch" | "attempt_mismatch" | "revision_mismatch" | "proof_key_mismatch" | "expired";

/** Atomic result from the one-time bootstrap repository. */
export type RuntimeBootstrapConsumptionResult = { readonly status: "consumed"; readonly receiptId: string } | { readonly status: "already_consumed" | "conflict" };

/** Persistence boundary that consumes one bootstrap claim exactly once. */
export interface RuntimeBootstrapRepository
{
	/** Atomically consumes the bootstrap and records the newly verified run proof key. */
	consumeAndBindProofKeyAtomically(claim: RuntimeBootstrapClaim): Promise<RuntimeBootstrapConsumptionResult>;
}

/** Result of validating and atomically consuming a runtime bootstrap. */
export type ConsumeRuntimeBootstrapResult = { readonly outcome: "consumed"; readonly receiptId: string } | { readonly outcome: "denied"; readonly reason: RuntimeBootstrapFailureReason | "bootstrap_replay" | "bootstrap_conflict" };

/** Replay policy attached to a proof-bound action capability. */
export type ActionReplayMode = "one_shot" | "idempotent";

/** Verified capability action submitted for exactly-once receipt handling. */
export interface ExecuteCapabilityActionCommand
{
	/** Compact ES256 DPoP-style proof presented by the runtime. */
	readonly compactProof: string;
	/** Trusted capability and observed HTTP request facts. */
	readonly expectation: CapabilityProofExpectation;
	/** Whether an identical replay denies or returns the canonical recorded result. */
	readonly replayMode: ActionReplayMode;
}

/** Request identity used by the receipt repository for capability-JTI replay control. */
export interface CapabilityActionIntent
{
	/** Proof-bound action capability identifier. */
	readonly jti: string;
	/** Digest binding the exact verified capability action and observed request. */
	readonly requestFingerprint: string;
	/** Explicit replay behavior for an identical request. */
	readonly replayMode: ActionReplayMode;
	/** Exact policy-enforcement audience. */
	readonly audience: string;
	/** Silo in which the capability is authoritative. */
	readonly siloId: string;
	/** Subject exercising the capability. */
	readonly subjectId: string;
	/** Projected Kubernetes service account. */
	readonly serviceAccountName: string;
	/** Exact Kubernetes namespace. */
	readonly namespace: string;
	/** Controller-owned workload kind. */
	readonly workloadKind: "job" | "deployment";
	/** Immutable controller workload UID. */
	readonly workloadUid: string;
	/** Immutable runtime Pod UID. */
	readonly podUid: string;
	/** Logical run identifier. */
	readonly runId: string;
	/** Current positive run attempt. */
	readonly attempt: number;
	/** Stable AgentService identifier. */
	readonly agentServiceId: string;
	/** Immutable AgentRevision identifier. */
	readonly agentRevisionId: string;
	/** RFC 7638 proof-key thumbprint registered to the workload. */
	readonly proofKeyThumbprint: string;
	/** Immutable capability catalog identifier. */
	readonly catalogId: string;
	/** Positive immutable capability catalog revision. */
	readonly catalogRevision: number;
	/** Digest of the immutable capability catalog. */
	readonly catalogDigest: string;
	/** Stable capability identifier within the catalog. */
	readonly capabilityId: string;
	/** Digest of the exact effective policy and grant set. */
	readonly effectivePolicyDigest: string;
	/** Exact resource kind being acted upon. */
	readonly resourceKind: string;
	/** Exact resource identifier being acted upon. */
	readonly resourceId: string;
	/** Exact action being performed. */
	readonly action: string;
	/** Digest of the RFC 8785 canonical action arguments. */
	readonly argumentsDigest: string;
}

/** Deferred action executor invoked only after a durable JTI reservation exists. */
export interface CapabilityActionExecutor<TResult>
{
	/** Executes the external action outside the repository transaction. */
	execute(): Promise<TResult>;
}

/** Canonical completed action receipt retained under the capability JTI. */
export interface CapabilityActionReceipt<TResult>
{
	/** Proof-bound action capability identifier that created the receipt. */
	readonly jti: string;
	/** Fingerprint of the exact verified request that produced the result. */
	readonly requestFingerprint: string;
	/** Replay policy fixed by the first execution. */
	readonly replayMode: ActionReplayMode;
	/** Canonical result returned only for allowed idempotent replays. */
	readonly result: TResult;
}

/** Atomic reservation result before external action I/O begins. */
export type CapabilityActionReservationResult<TResult> =
	| { readonly status: "reserved"; readonly reservationId: string }
	| { readonly status: "existing_reserved" | "existing_failed" }
	| { readonly status: "existing_succeeded"; readonly receipt: CapabilityActionReceipt<TResult> };

/** Compare-and-set result when completing a reserved action successfully. */
export type CapabilityActionSuccessResult<TResult> =
	| { readonly status: "succeeded"; readonly receipt: CapabilityActionReceipt<TResult> }
	| { readonly status: "conflict" };

/** Compare-and-set result when completing a reserved action as failed. */
export type CapabilityActionFailureResult = { readonly status: "failed" | "conflict" };

/** Persistence boundary that reserves before I/O and completes the durable receipt afterward. */
export interface CapabilityActionReceiptRepository
{
	/** Atomically creates a Reserved receipt or returns the existing durable JTI state. */
	reserve<TResult>(intent: CapabilityActionIntent): Promise<CapabilityActionReservationResult<TResult>>;
	/** Atomically transitions the exact Reserved receipt to Succeeded with its canonical result. */
	markSucceeded<TResult>(reservationId: string, result: TResult): Promise<CapabilityActionSuccessResult<TResult>>;
	/** Atomically transitions the exact Reserved receipt to Failed with a stable internal code. */
	markFailed(reservationId: string, failureCode: string): Promise<CapabilityActionFailureResult>;
}

/** Result of cryptographically verifying and executing a proof-bound capability action. */
export type ExecuteCapabilityActionResult<TResult> =
	| { readonly outcome: "executed" | "replayed"; readonly receipt: CapabilityActionReceipt<TResult> }
	| { readonly outcome: "denied"; readonly reason: CapabilityProofFailureReason | "invalid_replay_mode" | "jti_replay" | "action_reservation_failed" | "action_execution_failed" | "action_execution_ambiguous" };
