import type { Es256PublicJwk } from "@opencrane/models/authorization";
import type { AgentRuntimeProjectedTokenAudience, ManagedAgentRuntimeProjectedTokenAudience } from "@opencrane/contracts";

import type { RuntimeBootstrapRepository } from "./runtime-proof.types.js";

/** TokenReview-confirmed identity of a runtime workload presenting a projected credential. */
export interface RuntimeBootstrapReviewedIdentity
{
	/** Exact Kubernetes username returned by TokenReview. */
	readonly subject: string;
	/** Kubernetes namespace parsed from the reviewed subject. */
	readonly namespace: string;
	/** Kubernetes ServiceAccount name parsed from the reviewed subject. */
	readonly serviceAccountName: string;
	/** Kubernetes Pod UID asserted by TokenReview for this projected token. */
	readonly podUid: string;
}

/** Projected-token reviewer supplied by the OpenCrane process boundary. */
export interface RuntimeBootstrapTokenReviewer
{
	/** Reviews one token against the dedicated agent-runtime audience. */
	__Review(token: string): Promise<RuntimeBootstrapReviewedIdentity | null>;
}

/** Trusted server clock used to fence bootstrap expiry rather than a runtime-supplied time. */
export interface RuntimeBootstrapClock
{
	/** Returns the trusted current epoch milliseconds. */
	nowEpochMs(): number;
}

/** Body a runtime submits to bind its freshly generated public proof key to one bootstrap. */
export interface RuntimeBootstrapSubmission
{
	/** Opaque one-use bootstrap reference projected into the runtime Pod. */
	readonly bootstrapReference: string;
	/** Public P-256 key generated by the runtime for this run binding. */
	readonly proofPublicJwk: Es256PublicJwk;
	/** Runtime-proposed RFC 7638 thumbprint, re-derived from the public key before binding. */
	readonly proofKeyThumbprint: string;
}

/** Durable authority loaded for one bootstrap, split into its bootstrap and assignment sources. */
export interface RuntimeBootstrapExchangeRecord
{
	/** WorkloadBootstrap primary key equal to the opaque reference. */
	readonly bootstrapId: string;
	/** Silo recorded on the bootstrap row. */
	readonly bootstrapSiloId: string;
	/** Subject recorded on the bootstrap row. */
	readonly bootstrapSubjectId: string;
	/** Projected-token audience recorded on the bootstrap row. */
	readonly bootstrapAudience: AgentRuntimeProjectedTokenAudience | ManagedAgentRuntimeProjectedTokenAudience;
	/** ServiceAccount recorded on the bootstrap row. */
	readonly bootstrapServiceAccountName: string;
	/** Namespace recorded on the bootstrap row. */
	readonly bootstrapNamespace: string;
	/** Controller workload kind recorded on the bootstrap row. */
	readonly bootstrapWorkloadKind: "job" | "deployment";
	/** Controller workload UID recorded on the bootstrap row. */
	readonly bootstrapWorkloadUid: string;
	/** Run recorded on the bootstrap row. */
	readonly bootstrapRunId: string;
	/** AgentService recorded on the bootstrap row. */
	readonly bootstrapAgentServiceId: string;
	/** Attempt recorded on the bootstrap row. */
	readonly bootstrapAttempt: number;
	/** AgentRevision recorded on the bootstrap row. */
	readonly bootstrapAgentRevisionId: string;
	/** Hard bootstrap expiry in epoch milliseconds. */
	readonly bootstrapExpiresAtEpochMs: number;
	/** Silo recorded on the independent assignment row. */
	readonly assignmentSiloId: string;
	/** Subject recorded on the independent assignment row. */
	readonly assignmentSubjectId: string;
	/** Projected-token audience recorded on the independent assignment row. */
	readonly assignmentAudience: AgentRuntimeProjectedTokenAudience | ManagedAgentRuntimeProjectedTokenAudience;
	/** Controller workload kind recorded on the independent assignment row. */
	readonly assignmentWorkloadKind: "job" | "deployment";
	/** Controller workload UID recorded on the independent assignment row. */
	readonly assignmentWorkloadUid: string;
	/** Registered runtime Pod UID recorded on the independent assignment row. */
	readonly assignmentPodUid: string;
	/** Run recorded on the independent assignment row. */
	readonly assignmentRunId: string;
	/** AgentService recorded on the independent assignment row. */
	readonly assignmentAgentServiceId: string;
	/** Attempt recorded on the independent assignment row. */
	readonly assignmentAttempt: number;
	/** AgentRevision recorded on the independent assignment row. */
	readonly assignmentAgentRevisionId: string;
}

/** Persistence boundary that loads bootstrap authority and consumes it exactly once. */
export interface RuntimeBootstrapExchangeRepository extends RuntimeBootstrapRepository
{
	/** Loads the durable bootstrap and its independent assignment authority, or null when absent. */
	loadBootstrapExchange(bootstrapReference: string): Promise<RuntimeBootstrapExchangeRecord | null>;
}

/** Minimal structured logger surface required by the bootstrap HTTP boundary. */
export interface RuntimeBootstrapLogger
{
	/** Records a failed internal operation without serialising credentials or key material. */
	error(bindings: { readonly err: unknown; readonly operation: string }, message: string): void;
}

/** Dependencies of the workload-authenticated runtime bootstrap-exchange router. */
export interface RuntimeBootstrapRouterDependencies
{
	/** Dedicated projected-token identity reviewer for the runtime audience. */
	readonly tokenReviewer: RuntimeBootstrapTokenReviewer;
	/** Exact personal and managed namespaces in which runtime ServiceAccounts may exist. */
	readonly runtimeNamespaces: readonly [string, string];
	/** Durable bootstrap load-and-consume authority. */
	readonly repository: RuntimeBootstrapExchangeRepository;
	/** Trusted server clock. */
	readonly clock: RuntimeBootstrapClock;
	/** Shared process logger carrying request and trace context. */
	readonly logger: RuntimeBootstrapLogger;
}
