{{- if and .Values.certManager.enabled (eq .Values.certManager.mode "acme") .Values.certManager.acme.dns01.secretData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ dig "serviceAccountSecretRef" "name" "clouddns-dns01-solver" .Values.certManager.acme.dns01.config }}
  namespace: {{ .Values.certManager.namespace | default "cert-manager" }}
  labels:
    {{- include "opencrane.labels" . | nindent 4 }}
type: Opaque
data:
  {{ dig "serviceAccountSecretRef" "key" "key.json" .Values.certManager.acme.dns01.config }}: {{ .Values.certManager.acme.dns01.secretData | b64enc }}
{{- end }}
